package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.MusicMst;
import greendao.MusicResultDBHR;

import greendao.MusicMstDao;
import greendao.MusicResultDBHRDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicMstDaoConfig;
    private final DaoConfig musicResultDBHRDaoConfig;

    private final MusicMstDao musicMstDao;
    private final MusicResultDBHRDao musicResultDBHRDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicMstDaoConfig = daoConfigMap.get(MusicMstDao.class).clone();
        musicMstDaoConfig.initIdentityScope(type);

        musicResultDBHRDaoConfig = daoConfigMap.get(MusicResultDBHRDao.class).clone();
        musicResultDBHRDaoConfig.initIdentityScope(type);

        musicMstDao = new MusicMstDao(musicMstDaoConfig, this);
        musicResultDBHRDao = new MusicResultDBHRDao(musicResultDBHRDaoConfig, this);

        registerDao(MusicMst.class, musicMstDao);
        registerDao(MusicResultDBHR.class, musicResultDBHRDao);
    }
    
    public void clear() {
        musicMstDaoConfig.getIdentityScope().clear();
        musicResultDBHRDaoConfig.getIdentityScope().clear();
    }

    public MusicMstDao getMusicMstDao() {
        return musicMstDao;
    }

    public MusicResultDBHRDao getMusicResultDBHRDao() {
        return musicResultDBHRDao;
    }

}
