package greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.MusicMst;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MUSIC_MST.
*/
public class MusicMstDao extends AbstractDao<MusicMst, Long> {

    public static final String TABLENAME = "MUSIC_MST";

    /**
     * Properties of entity MusicMst.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Nha = new Property(2, String.class, "nha", false, "NHA");
        public final static Property Version = new Property(3, String.class, "version", false, "VERSION");
        public final static Property Genre = new Property(4, String.class, "genre", false, "GENRE");
        public final static Property Artist = new Property(5, String.class, "artist", false, "ARTIST");
        public final static Property BpmFrom = new Property(6, Integer.class, "bpmFrom", false, "BPM_FROM");
        public final static Property BpmTo = new Property(7, Integer.class, "bpmTo", false, "BPM_TO");
        public final static Property Difficult = new Property(8, String.class, "difficult", false, "DIFFICULT");
        public final static Property Notes = new Property(9, Integer.class, "notes", false, "NOTES");
        public final static Property ScratchNotes = new Property(10, Integer.class, "scratchNotes", false, "SCRATCH_NOTES");
        public final static Property ChargeNotes = new Property(11, Integer.class, "chargeNotes", false, "CHARGE_NOTES");
        public final static Property BackSpinScratchNotes = new Property(12, Integer.class, "backSpinScratchNotes", false, "BACK_SPIN_SCRATCH_NOTES");
        public final static Property SortNumInDifficult = new Property(13, Integer.class, "sortNumInDifficult", false, "SORT_NUM_IN_DIFFICULT");
        public final static Property MstVersion = new Property(14, String.class, "mstVersion", false, "MST_VERSION");
        public final static Property InsDate = new Property(15, java.util.Date.class, "insDate", false, "INS_DATE");
        public final static Property UpdDate = new Property(16, java.util.Date.class, "updDate", false, "UPD_DATE");
        public final static Property MusicResultIdDBHR = new Property(17, long.class, "musicResultIdDBHR", false, "MUSIC_RESULT_ID_DBHR");
    };

    private DaoSession daoSession;


    public MusicMstDao(DaoConfig config) {
        super(config);
    }
    
    public MusicMstDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MUSIC_MST' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'NHA' TEXT," + // 2: nha
                "'VERSION' TEXT," + // 3: version
                "'GENRE' TEXT," + // 4: genre
                "'ARTIST' TEXT," + // 5: artist
                "'BPM_FROM' INTEGER," + // 6: bpmFrom
                "'BPM_TO' INTEGER," + // 7: bpmTo
                "'DIFFICULT' TEXT," + // 8: difficult
                "'NOTES' INTEGER," + // 9: notes
                "'SCRATCH_NOTES' INTEGER," + // 10: scratchNotes
                "'CHARGE_NOTES' INTEGER," + // 11: chargeNotes
                "'BACK_SPIN_SCRATCH_NOTES' INTEGER," + // 12: backSpinScratchNotes
                "'SORT_NUM_IN_DIFFICULT' INTEGER," + // 13: sortNumInDifficult
                "'MST_VERSION' TEXT," + // 14: mstVersion
                "'INS_DATE' INTEGER," + // 15: insDate
                "'UPD_DATE' INTEGER," + // 16: updDate
                "'MUSIC_RESULT_ID_DBHR' INTEGER NOT NULL );"); // 17: musicResultIdDBHR
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MUSIC_MST'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MusicMst entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String nha = entity.getNha();
        if (nha != null) {
            stmt.bindString(3, nha);
        }
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(4, version);
        }
 
        String genre = entity.getGenre();
        if (genre != null) {
            stmt.bindString(5, genre);
        }
 
        String artist = entity.getArtist();
        if (artist != null) {
            stmt.bindString(6, artist);
        }
 
        Integer bpmFrom = entity.getBpmFrom();
        if (bpmFrom != null) {
            stmt.bindLong(7, bpmFrom);
        }
 
        Integer bpmTo = entity.getBpmTo();
        if (bpmTo != null) {
            stmt.bindLong(8, bpmTo);
        }
 
        String difficult = entity.getDifficult();
        if (difficult != null) {
            stmt.bindString(9, difficult);
        }
 
        Integer notes = entity.getNotes();
        if (notes != null) {
            stmt.bindLong(10, notes);
        }
 
        Integer scratchNotes = entity.getScratchNotes();
        if (scratchNotes != null) {
            stmt.bindLong(11, scratchNotes);
        }
 
        Integer chargeNotes = entity.getChargeNotes();
        if (chargeNotes != null) {
            stmt.bindLong(12, chargeNotes);
        }
 
        Integer backSpinScratchNotes = entity.getBackSpinScratchNotes();
        if (backSpinScratchNotes != null) {
            stmt.bindLong(13, backSpinScratchNotes);
        }
 
        Integer sortNumInDifficult = entity.getSortNumInDifficult();
        if (sortNumInDifficult != null) {
            stmt.bindLong(14, sortNumInDifficult);
        }
 
        String mstVersion = entity.getMstVersion();
        if (mstVersion != null) {
            stmt.bindString(15, mstVersion);
        }
 
        java.util.Date insDate = entity.getInsDate();
        if (insDate != null) {
            stmt.bindLong(16, insDate.getTime());
        }
 
        java.util.Date updDate = entity.getUpdDate();
        if (updDate != null) {
            stmt.bindLong(17, updDate.getTime());
        }
        stmt.bindLong(18, entity.getMusicResultIdDBHR());
    }

    @Override
    protected void attachEntity(MusicMst entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MusicMst readEntity(Cursor cursor, int offset) {
        MusicMst entity = new MusicMst( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nha
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // version
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // genre
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // artist
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // bpmFrom
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // bpmTo
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // difficult
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // notes
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // scratchNotes
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // chargeNotes
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // backSpinScratchNotes
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // sortNumInDifficult
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // mstVersion
            cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)), // insDate
            cursor.isNull(offset + 16) ? null : new java.util.Date(cursor.getLong(offset + 16)), // updDate
            cursor.getLong(offset + 17) // musicResultIdDBHR
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MusicMst entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNha(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVersion(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGenre(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setArtist(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBpmFrom(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setBpmTo(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setDifficult(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setNotes(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setScratchNotes(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setChargeNotes(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setBackSpinScratchNotes(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setSortNumInDifficult(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setMstVersion(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setInsDate(cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)));
        entity.setUpdDate(cursor.isNull(offset + 16) ? null : new java.util.Date(cursor.getLong(offset + 16)));
        entity.setMusicResultIdDBHR(cursor.getLong(offset + 17));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MusicMst entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MusicMst entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMusicResultDBHRDao().getAllColumns());
            builder.append(" FROM MUSIC_MST T");
            builder.append(" LEFT JOIN MUSIC_RESULT_DBHR T0 ON T.'MUSIC_RESULT_ID_DBHR'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MusicMst loadCurrentDeep(Cursor cursor, boolean lock) {
        MusicMst entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        MusicResultDBHR musicResultDBHR = loadCurrentOther(daoSession.getMusicResultDBHRDao(), cursor, offset);
         if(musicResultDBHR != null) {
            entity.setMusicResultDBHR(musicResultDBHR);
        }

        return entity;    
    }

    public MusicMst loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MusicMst> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MusicMst> list = new ArrayList<MusicMst>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MusicMst> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MusicMst> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
