package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MUSIC_RESULT__DBHR.
 */
public class MusicResult_DBHR {

    private Long id;
    private String clearLamp;
    private Integer exScore;
    private Integer bp;
    private Double scoreRank;
    private Double scoreRate;
    private Double missRate;
    private String memoProgress;
    private String memoOther;
    private String pGreat;
    private String great;
    private String good;
    private String bad;
    private String poor;
    private String comboBreak;
    private java.util.Date insDate;
    private java.util.Date updDate;

    public MusicResult_DBHR() {
    }

    public MusicResult_DBHR(Long id) {
        this.id = id;
    }

    public MusicResult_DBHR(Long id, String clearLamp, Integer exScore, Integer bp, Double scoreRank, Double scoreRate, Double missRate, String memoProgress, String memoOther, String pGreat, String great, String good, String bad, String poor, String comboBreak, java.util.Date insDate, java.util.Date updDate) {
        this.id = id;
        this.clearLamp = clearLamp;
        this.exScore = exScore;
        this.bp = bp;
        this.scoreRank = scoreRank;
        this.scoreRate = scoreRate;
        this.missRate = missRate;
        this.memoProgress = memoProgress;
        this.memoOther = memoOther;
        this.pGreat = pGreat;
        this.great = great;
        this.good = good;
        this.bad = bad;
        this.poor = poor;
        this.comboBreak = comboBreak;
        this.insDate = insDate;
        this.updDate = updDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClearLamp() {
        return clearLamp;
    }

    public void setClearLamp(String clearLamp) {
        this.clearLamp = clearLamp;
    }

    public Integer getExScore() {
        return exScore;
    }

    public void setExScore(Integer exScore) {
        this.exScore = exScore;
    }

    public Integer getBp() {
        return bp;
    }

    public void setBp(Integer bp) {
        this.bp = bp;
    }

    public Double getScoreRank() {
        return scoreRank;
    }

    public void setScoreRank(Double scoreRank) {
        this.scoreRank = scoreRank;
    }

    public Double getScoreRate() {
        return scoreRate;
    }

    public void setScoreRate(Double scoreRate) {
        this.scoreRate = scoreRate;
    }

    public Double getMissRate() {
        return missRate;
    }

    public void setMissRate(Double missRate) {
        this.missRate = missRate;
    }

    public String getMemoProgress() {
        return memoProgress;
    }

    public void setMemoProgress(String memoProgress) {
        this.memoProgress = memoProgress;
    }

    public String getMemoOther() {
        return memoOther;
    }

    public void setMemoOther(String memoOther) {
        this.memoOther = memoOther;
    }

    public String getPGreat() {
        return pGreat;
    }

    public void setPGreat(String pGreat) {
        this.pGreat = pGreat;
    }

    public String getGreat() {
        return great;
    }

    public void setGreat(String great) {
        this.great = great;
    }

    public String getGood() {
        return good;
    }

    public void setGood(String good) {
        this.good = good;
    }

    public String getBad() {
        return bad;
    }

    public void setBad(String bad) {
        this.bad = bad;
    }

    public String getPoor() {
        return poor;
    }

    public void setPoor(String poor) {
        this.poor = poor;
    }

    public String getComboBreak() {
        return comboBreak;
    }

    public void setComboBreak(String comboBreak) {
        this.comboBreak = comboBreak;
    }

    public java.util.Date getInsDate() {
        return insDate;
    }

    public void setInsDate(java.util.Date insDate) {
        this.insDate = insDate;
    }

    public java.util.Date getUpdDate() {
        return updDate;
    }

    public void setUpdDate(java.util.Date updDate) {
        this.updDate = updDate;
    }

}
